version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back_ops
    ports:
      - '4557:80'
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html

  db:
    image: 'mariadb'
    container_name: database_ops
    ports:
      - '3307'
    restart: always
    environment:
      MYSQL_DATABASE: COD
      MYSQL_ROOT_PASSWORD: calloc
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
